version: 1

before:
  hooks:
#    - pnpm install
#    - go mod tidy

git:
  tag_sort: -version:creatordate
  prerelease_suffix: "-"

project_name: faucet

builds:
  - id: "cli"
    binary: "bin/faucet"
    main: "main.go"

    flags:
      - -v

    ldflags:
      - -X "github.com/CoopHive/faucet.coophive.network/config.version={{.Version}}"
      - -X "github.com/CoopHive/faucet.coophive.network/config.commitSha={{.ShortCommit}}"
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

      - goos: windows
        goarch: arm

    dir: "." #go.mod

    no_unique_dist_dir: true

universal_binaries:
  - name_template: 'faucet-darwin-universal' #binary name
    id: faucet
    ids:
      - cli
      - faucet
      - faucet-universal
    replace: false

    hooks:
      pre: echo "pre"
      post: echo {{ .Path }}

archives:
  - format: binary
    #  - format: tar.gz
    #    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip


changelog:
  sort: asc
  filters:
#    exclude:
#      - "^docs:"
#      - "^test:"

release:
  mode: append
  draft: true
  replace_existing_draft: true
  #  make_latest: true
  prerelease: auto #if rc1

#https://goreleaser.com/customization/release/#github

#https://goreleaser.com/customization/universalbinaries/

