version: '3.8'
services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:8080/']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
#    volumes:
#      - ./temp:/app


  sepolia:
    env_file:
      - .env.sepolia
    image: ghcr.io/coophive/faucet:latest
    restart: always
    ports:
      - '8081:8080'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:8080/' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s