version: '3.8'
services:
  sepolia:
    environment:
      NETWORK: sepolia
    env_file:
      - .env.sepolia
    image: ghcr.io/coophive/faucet:latest
    restart: always
    ports:
      - '9000:8080'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:8080/' ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
