name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          cache-dependency-path: go.sum
          cache: true
          go-version-file: go.mod

      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "./web/pnpm-lock.yaml"
          node-version: "20.11.0"
          check-latest: true

      - name: Generate
        run: go generate

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          cache-dependency-path: go.sum
          cache: true
          go-version-file: go.mod

      - name: golangci-lint
        continue-on-error: true #FIXME:
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "./web/pnpm-lock.yaml"
          node-version: "20.11.0"
          check-latest: true

      - run: pnpm install
        working-directory: web

      - run: pnpm prettier --check 'src/**/*.{css,html,js,svelte}'
        working-directory: web
