name: Deploy to Surge

on:
  push:
    branches:
      - main
    tags:
      - '*'
      - '**'
#    paths:
#      - '.github/workflows/deploy.yml'

  pull_request: #FIXME: remove after testing
    branches: [ "main" ]

  workflow_dispatch:

env:
  VITE_BASE_URL: 'http' #TODO:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./web
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: surge

    env:
      domain: taskmon.surge.sh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.6
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "./web/pnpm-lock.yaml"
          node-version: "20.11.0"
          check-latest: true

      - name: Extract Domain
        id: extract_domain
        run: |
          ref=$(git rev-parse --abbrev-ref HEAD)
          sref=${ref//\//-}
          echo "preview_domain=$sref-$domain" >> $GITHUB_OUTPUT

      - name: Get working directory
        id: wkdir
        run: |
          echo "wkdir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Preview to ${{ steps.extract_domain.outputs.preview_domain }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ steps.extract_domain.outputs.preview_domain }}
          project: ${{ steps.wkdir.outputs.wkdir }}/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      - name: Deploy to ${env.domain}
        if:
          ${{ startsWith(github.ref, 'refs/tags/') || github.ref ==
          'refs/heads/main' }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${env.domain}
          project: ${{ steps.wkdir.outputs.wkdir }}/dist
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}